spring:
  application:
    name: grafana-prometheus
  config:
    bloodpressure-url: http://localhost:9999/api/v1/patients


server:
  port: 9900


management:
  endpoint:
    show-details: always
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
            - prometheus
            - health
            - info
            - metrics
            - httptrace
            - threaddump
            - loggers
            - caches
            - env
            - configprops
  metrics:
    export:
      prometheus:
        enabled: true